config/routes.rb
Rails.application.routes.draw do
  resources :liquidacions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/liquidacion.rb
class Liquidacion < ApplicationRecord

    def self.to_csv(options = {encoding: 'UTF-8'})
      CSV.generate(options) do |csv|
        csv << column_names
        all.each do |liquidacions|
          csv << liquidacions.attributes.values_at(*column_names)
        end
      end
    end

end
  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/liquidacions_controller.rb
class LiquidacionsController < ApplicationController
  before_action :set_liquidacion, only: [:show, :edit, :update, :destroy]

  # GET /liquidacions
  # GET /liquidacions.json
  def index
    @liquidacions = Liquidacion.order(:created_at)
    respond_to do |format|
      format.xls #{ send_data @liquidacions.to_csv(col_sep: "\t"),filename: 'ListadoLiquidaciones.xls',encoding: 'ISO-8859-1'}
      format.html
      format.csv do
        headers['Content-Disposition'] = "attachment; filename=\"ListadoLiquidaciones.csv\""
        headers['Content-Type'] ||= 'text/csv'
      end
      
    end
  end

  # GET /liquidacions/1
  # GET /liquidacions/1.json
  def show
  end

  # GET /liquidacions/new
  def new
    @liquidacion = Liquidacion.new
  end

  # GET /liquidacions/1/edit
  def edit
  end

  # POST /liquidacions
  # POST /liquidacions.json
  def create
    @liquidacion = Liquidacion.new(liquidacion_params)

    respond_to do |format|
      if @liquidacion.save
        UserMailer.bienvenidos_email(@liquidacion).deliver_now
        format.html { redirect_to @liquidacion, notice: 'Liquidacion fue creado correctamente' }
        format.json { render :show, status: :created, location: @liquidacion }
      else
        format.html { render :new }
        format.json { render json: @liquidacion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /liquidacions/1
  # PATCH/PUT /liquidacions/1.json
  def update
    respond_to do |format|
      if @liquidacion.update(liquidacion_params)
        format.html { redirect_to @liquidacion, notice: 'Liquidacion fue modificada correctamente' }
        format.json { render :show, status: :ok, location: @liquidacion }
      else
        format.html { render :edit }
        format.json { render json: @liquidacion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /liquidacions/1
  # DELETE /liquidacions/1.json
  def destroy
    @liquidacion.destroy
    respond_to do |format|
      format.html { redirect_to liquidacions_url, notice: 'Liquidacion fue eliminada' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_liquidacion
      @liquidacion = Liquidacion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def liquidacion_params
      params.require(:liquidacion).permit(:fecha_ini, :fecha_fin, :cargo, :contrato, :termina, :salario, :auxilio, :horas_ex_diur, :horas_ex_noc, :recargos_noc, :domi_ordinarios, :horas_ex_domi_diur, :horas_ex_domi_noc, :otros, :concepto_otros, :sueldo_promedio, :prima_extra, :valor_mes, :valor_dia, :valor_hora, :recargo_nocturno, :hora_extra_diurna, :hora_extra_nocturna, :hora_ordinaria_dominical, :hora_extra_dominical_diurna, :hora_extra_dominical_nocturna, :fecha_ini_vacas, :fecha_fin_vacas, :vacaciones, :indemniza_art65, :indemniza_art64, :calc_art64, :check65, :fecha_ini_pactada, :fecha_fin_pactada, :num_pro, :fecha_ini_pro1, :date, :fecha_ini_pro2, :fecha_ini_pro3, :fecha_ini_pro4, :fecha_fin_pro1, :fecha_fin_pro2, :fecha_fin_pro3, :fecha_fin_pro4, :fecha_ini_presta, :fecha_fin_presta, :cesantias, :inte_cesantias, :prima, :total_prestaciones, :sueldo_pendiente, :aux_pendiente, :reajuste_pendiente, :otros_pendiente, :total_pendiente,:total, :nombres, :correo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/liquidacions_helper.rb
module LiquidacionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Administración LiquidaTadeo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <nav class="navbar navbar-expand-lg navbar-light bg-light">   
  <%= image_tag 'logo.png', width: '1300px' %>
</nav>
    <%= yield %>
  </body>
</html>

app/views/liquidacions/_form.html.erb
<div class="panel panel-default">
<div class="panel-body">

<%= form_with(model: liquidacion, local: true) do |form| %>
  <% if liquidacion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(liquidacion.errors.count, "error") %> prohibited this liquidacion from being saved:</h2>

      <ul>
      <% liquidacion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :fecha_ini %>
    <%= form.date_select :fecha_ini %>
  </div>

  <div class="field">
    <%= form.label :fecha_fin %>
    <%= form.date_select :fecha_fin %>
  </div>

  <div class="field">
    <%= form.label :cargo %>
    <%= form.text_area :cargo %>
  </div>

  <div class="field">
    <%= form.label :contrato %>
    <%= form.text_area :contrato %>
  </div>

  <div class="field">
    <%= form.label :termina %>
    <%= form.text_area :termina %>
  </div>

  <div class="field">
    <%= form.label :salario %>
    <%= form.text_field :salario %>
  </div>


  <div class="field">
    <%= form.label :sueldo_promedio %>
    <%= form.text_field :sueldo_promedio %>
  </div>

  <div class="field">
    <%= form.label :vacaciones %>
    <%= form.text_field :vacaciones %>
  </div>

  <div class="field">
    <%= form.label :indemniza_art65 %>
    <%= form.text_field :indemniza_art65 %>
  </div>

  <div class="field">
    <%= form.label :indemniza_art64 %>
    <%= form.text_field :indemniza_art64 %>
  </div>

  <div class="field">
    <%= form.label :cesantias %>
    <%= form.text_field :cesantias %>
  </div>

  <div class="field">
    <%= form.label :inte_cesantias %>
    <%= form.text_field :inte_cesantias %>
  </div>

  <div class="field">
    <%= form.label :prima %>
    <%= form.text_field :prima %>
  </div>

  <div class="field">
    <%= form.label :total_prestaciones %>
    <%= form.text_field :total_prestaciones %>
  </div>
  
  
  <div class="field">
    <%= form.label :total %>
    <%= form.text_field :total %>
  </div>

  <div class="field">
    <%= form.label :nombres %>
    <%= form.text_area :nombres %>
  </div>

  <div class="field">
    <%= form.label :correo %>
    <%= form.text_area :correo %>
  </div>

  <div class="field">
  <%= form.label :Fecha_creación %>
  <%= form.text_area :created_at %>
 </div>
  

  <div class="actions">
    <%= form.submit %>
    </div>
    </div>
  <% end %>
    </div>
    </div>

app/views/liquidacions/edit.html.erb
<h1>Editing Liquidacion</h1>

<%= render 'form', liquidacion: @liquidacion %>

<%= link_to 'Show', @liquidacion %> |
<%= link_to 'Back', liquidacions_path %>

app/views/liquidacions/index.csv.erb
<%- headers = ['Fecha ini',
'Fecha fin',
'Cargo',
'Contrato',
'Termina',
'Salario',
'Auxilio',
'Horas ex diur',
'Horas ex noc',
'Recargos noc',
'Domi ordinarios',
'Horas ex domi diur',
'Horas ex domi noc',
'Otros',
'Concepto otros',
'Sueldo promedio',
'Prima extra',
'Valor mes',
'Valor día float',
'Valor hora',
'Recargo nocturno',
'Hora extra diurna',
'Hora extra nocturna',
'Hora ordinaria dominical',
'Hora extra dominical diurna',
'Hora extra dominical nocturna',
'Fecha ini vacas',
'Fecha fin vacas',
'Vacaciones',
'Indemniza art65',
'Indemniza art64',
'Calc art64',
'Check65',
'Fecha ini pactada',
'Fecha fin pactada',
'Num pro',
'Fecha ini pro1',
'Date',
'Fecha ini pro2',
'Fecha ini pro3',
'Fecha ini pro4',
'Fecha fin pro1',
'Fecha fin pro2',
'Fecha fin pro3',
'Fecha fin pro4',
'Fecha ini presta',
'Fecha fin presta',
'Cesantias',
'Inte cesantias',
'Prima',
'Total prestaciones',
'Sueldo pendiente',
'Aux pendiente',
'Reajuste pendiente',
'Otros pendiente',
'Total pendiente',
'Total',
'Nombres',
'Correo',
'Fecha creación'] -%>
<%= CSV.generate_line headers %>
<%- @liquidacions.each do |liquidacion| -%>
<%= CSV.generate_line([liquidacion.fecha_ini ,
liquidacion.fecha_fin ,
liquidacion.cargo ,
liquidacion.contrato ,
liquidacion.termina ,
liquidacion.salario ,
liquidacion.auxilio ,
liquidacion.horas_ex_diur ,
liquidacion.horas_ex_noc ,
liquidacion.recargos_noc ,
liquidacion.domi_ordinarios ,
liquidacion.horas_ex_domi_diur ,
liquidacion.horas_ex_domi_noc ,
liquidacion.otros ,
liquidacion.concepto_otros ,
liquidacion.sueldo_promedio ,
liquidacion.prima_extra ,
liquidacion.valor_mes ,
liquidacion.valor_dia ,
liquidacion.valor_hora ,
liquidacion.recargo_nocturno ,
liquidacion.hora_extra_diurna ,
liquidacion.hora_extra_nocturna ,
liquidacion.hora_ordinaria_dominical,
liquidacion.hora_extra_dominical_diurna, 
liquidacion.hora_extra_dominical_nocturna,
liquidacion.fecha_ini_vacas ,
liquidacion.fecha_fin_vacas ,
liquidacion.vacaciones ,
liquidacion.indemniza_art65 ,
liquidacion.indemniza_art64 ,
liquidacion.calc_art64 ,
liquidacion.check65 ,
liquidacion.fecha_ini_pactada ,
liquidacion.fecha_fin_pactada ,
liquidacion.num_pro ,
liquidacion.fecha_ini_pro1 ,
liquidacion.date ,
liquidacion.fecha_ini_pro2 ,
liquidacion.fecha_ini_pro3 ,
liquidacion.fecha_ini_pro4 ,
liquidacion.fecha_fin_pro1 ,
liquidacion.fecha_fin_pro2 ,
liquidacion.fecha_fin_pro3 ,
liquidacion.fecha_fin_pro4 ,
liquidacion.fecha_ini_presta ,
liquidacion.fecha_fin_presta ,
liquidacion.cesantias ,
liquidacion.inte_cesantias ,
liquidacion.prima ,
liquidacion.total_prestaciones ,
liquidacion.sueldo_pendiente ,
liquidacion.aux_pendiente ,
liquidacion.reajuste_pendiente ,
liquidacion.otros_pendiente ,
liquidacion.total_pendiente ,
liquidacion.total ,
liquidacion.nombres ,
liquidacion.correo,
liquidacion.created_at]).html_safe -%>
<%- end -%>

app/views/liquidacions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Historico liquidaciones</h1>
<%= link_to image_tag("xls.png"), liquidacions_path(format: "xls") %>
<%= link_to 'XLS ', liquidacions_path(format: "xls") %>|

<%= link_to image_tag("csv.png"), liquidacions_path(format: "csv") %>
<%= link_to 'CSV ', liquidacions_path(format: "csv") %>

<table class="table table-striped table-bordered table-hover table-sm ">
  <thead> 
    <tr>
      <th>Fecha inicio</th>
      <th>Fecha fin</th>
      <th>Cargo</th>
      <th>Contrato</th>
      <th>Termina</th>
      <th>Salario</th>
      <th>Sueldo promedio</th>
      <th>Vacaciones</th>
      <th>Indemniza Art65</th>
      <th>Indemniza Art64</th>
      <th>Cesantias</th>
      <th>Inte cesantias</th>
      <th>Prima</th>
      <th>Total prestaciones</th>
      <th>Total</th>
      <th>Nombres</th>
      <th>Correo</th>
      <th>Fecha Creación</th>

      <th colspan="3">Acciones</th>
    </tr>
  </thead>

  <tbody>
    <% @liquidacions.each do |liquidacion| %>
      <tr>
        <td><%= liquidacion.fecha_ini %></td>
        <td><%= liquidacion.fecha_fin %></td>
        <td><%= liquidacion.cargo %></td>
        <td><%= liquidacion.contrato %></td>
        <td><%= liquidacion.termina %></td>
        <td><%= liquidacion.salario %></td>
        <td><%= liquidacion.sueldo_promedio %></td>
        <td><%= liquidacion.vacaciones %></td>
        <td><%= liquidacion.indemniza_art65 %></td>
        <td><%= liquidacion.indemniza_art64 %></td>
        <td><%= liquidacion.cesantias %></td>
        <td><%= liquidacion.inte_cesantias %></td>
        <td><%= liquidacion.prima %></td>
        <td><%= liquidacion.total_prestaciones %></td>
        <td><%= liquidacion.total%></td>        
        <td><%= liquidacion.nombres %></td>
        <td><%= liquidacion.correo %></td>
        <td><%= liquidacion.created_at%></td>

          <td><%= link_to 'Mostrar', liquidacion , class: 'label label-info'%></td>
        <td><%= link_to 'Editar', edit_liquidacion_path(liquidacion) , class: 'label label-success'%></td>
        <td><%= button_to 'Eliminar', liquidacion, method: :delete,class: 'button', :onclick => "return confirm('¿Esta seguro de eliminar este registro?')" %></td> 
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to image_tag("xls.png"), liquidacions_path(format: "xls") %>
<%= link_to 'XLS ', liquidacions_path(format: "xls") %>|

<%= link_to image_tag("csv.png"), liquidacions_path(format: "csv") %>
<%= link_to 'CSV ', liquidacions_path(format: "csv") %>
<br>
<br>
<%= link_to 'Nueva Liquidación', new_liquidacion_path %>

app/views/liquidacions/index.xls.erb
<table border="1">
  <tr>
  <th>Fecha ini</th>
  <th>Fecha fin</th>
  <th>Cargo</th>
  <th>Contrato</th>
  <th>Termina</th>
  <th>Salario</th>
  <th>Auxilio</th>
  <th>Horas ex diur</th>
  <th>Horas ex noc</th>
  <th>Recargos noc</th>
  <th>Domi ordinarios</th>
  <th>Horas ex domi diur</th>
  <th>Horas ex domi noc</th>
  <th>Otros</th>
  <th>Concepto otros</th>
  <th>Sueldo promedio</th>
  <th>Prima extra</th>
  <th>Valor mes</th>
  <th>Valor día float</th>
  <th>Valor hora</th>
  <th>Recargo nocturno</th>
  <th>Hora extra diurna</th>
  <th>Hora extra nocturna</th>
  <th>Hora ordinaria dominical</th>
  <th>Hora extra dominical diurna</th>
  <th>Hora extra dominical nocturna</th>
  <th>Fecha ini vacas</th>
  <th>Fecha fin vacas</th>
  <th>Vacaciones</th>
  <th>Indemniza art65</th>
  <th>Indemniza art64</th>
  <th>Calc art64</th>
  <th>Check65</th>
  <th>Fecha ini pactada</th>
  <th>Fecha fin pactada</th>
  <th>Num pro</th>
  <th>Fecha ini pro1</th>
  <th>Date</th>
  <th>Fecha ini pro2</th>
  <th>Fecha ini pro3</th>
  <th>Fecha ini pro4</th>
  <th>Fecha fin pro1</th>
  <th>Fecha fin pro2</th>
  <th>Fecha fin pro3</th>
  <th>Fecha fin pro4</th>
  <th>Fecha ini presta</th>
  <th>Fecha fin presta</th>
  <th>Cesantias</th>
  <th>Inte cesantias</th>
  <th>Prima</th>
  <th>Total prestaciones</th>
  <th>Sueldo pendiente</th>
  <th>Aux pendiente</th>
  <th>Reajuste pendiente</th>
  <th>Otros pendiente</th>
  <th>Total pendiente</th>
  <th>Total</th>
  <th>Nombres</th>
  <th>Correo</th>
  <th>Fecha creación</th>

  </tr>
  <% @liquidacions.each do |liquidacion| %>
  <tr>
        <td><%= liquidacion.fecha_ini %></td>
        <td><%= liquidacion.fecha_fin %></td>
        <td><%= liquidacion.cargo %></td>
        <td><%= liquidacion.contrato %></td>
        <td><%= liquidacion.termina %></td>
        <td><%= liquidacion.salario %></td>
        <td><%= liquidacion.auxilio %></td>
        <td><%= liquidacion.horas_ex_diur %></td>
        <td><%= liquidacion.horas_ex_noc %></td>
        <td><%= liquidacion.recargos_noc %></td>
        <td><%= liquidacion.domi_ordinarios %></td>
        <td><%= liquidacion.horas_ex_domi_diur %></td>
        <td><%= liquidacion.horas_ex_domi_noc %></td>
        <td><%= liquidacion.otros %></td>
        <td><%= liquidacion.concepto_otros %></td>
        <td><%= liquidacion.sueldo_promedio %></td>
        <td><%= liquidacion.prima_extra %></td>
        <td><%= liquidacion.valor_mes %></td>
        <td><%= liquidacion.valor_dia %></td>
        <td><%= liquidacion.valor_hora %></td>
        <td><%= liquidacion.recargo_nocturno %></td>
        <td><%= liquidacion.hora_extra_diurna %></td>
        <td><%= liquidacion.hora_extra_nocturna %></td>
        <td><%= liquidacion.hora_ordinaria_dominical %></td>
        <td><%= liquidacion.hora_extra_dominical_diurna %></td>
        <td><%= liquidacion.hora_extra_dominical_nocturna %></td>
        <td><%= liquidacion.fecha_ini_vacas %></td>
        <td><%= liquidacion.fecha_fin_vacas %></td>
        <td><%= liquidacion.vacaciones %></td>
        <td><%= liquidacion.indemniza_art65 %></td>
        <td><%= liquidacion.indemniza_art64 %></td>
        <td><%= liquidacion.calc_art64 %></td>
        <td><%= liquidacion.check65 %></td>
        <td><%= liquidacion.fecha_ini_pactada %></td>
        <td><%= liquidacion.fecha_fin_pactada %></td>
        <td><%= liquidacion.num_pro %></td>
        <td><%= liquidacion.fecha_ini_pro1 %></td>
        <td><%= liquidacion.date %></td>
        <td><%= liquidacion.fecha_ini_pro2 %></td>
        <td><%= liquidacion.fecha_ini_pro3 %></td>
        <td><%= liquidacion.fecha_ini_pro4 %></td>
        <td><%= liquidacion.fecha_fin_pro1 %></td>
        <td><%= liquidacion.fecha_fin_pro2 %></td>
        <td><%= liquidacion.fecha_fin_pro3 %></td>
        <td><%= liquidacion.fecha_fin_pro4 %></td>
        <td><%= liquidacion.fecha_ini_presta %></td>
        <td><%= liquidacion.fecha_fin_presta %></td>
        <td><%= liquidacion.cesantias %></td>
        <td><%= liquidacion.inte_cesantias %></td>
        <td><%= liquidacion.prima %></td>
        <td><%= liquidacion.total_prestaciones %></td>
        <td><%= liquidacion.sueldo_pendiente %></td>
        <td><%= liquidacion.aux_pendiente %></td>
        <td><%= liquidacion.reajuste_pendiente %></td>
        <td><%= liquidacion.otros_pendiente %></td>
        <td><%= liquidacion.total_pendiente %></td>
        <td><%= liquidacion.total %></td>
        <td><%= liquidacion.nombres %></td>
        <td><%= liquidacion.correo %></td>
        <td><%= liquidacion.created_at %></td>

  </tr>
  <% end %>
</table>

app/views/liquidacions/new.html.erb
<h1>New Liquidacion</h1>

<%= render 'form', liquidacion: @liquidacion %>

<%= link_to 'Back', liquidacions_path %>

app/views/liquidacions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fecha ini:</strong>
  <%= @liquidacion.fecha_ini %>
</p>

<p>
  <strong>Fecha fin:</strong>
  <%= @liquidacion.fecha_fin %>
</p>

<p>
  <strong>Cargo:</strong>
  <%= @liquidacion.cargo %>
</p>

<p>
  <strong>Contrato:</strong>
  <%= @liquidacion.contrato %>
</p>

<p>
  <strong>Termina:</strong>
  <%= @liquidacion.termina %>
</p>

<p>
  <strong>Salario:</strong>
  <%= @liquidacion.salario %>
</p>

<p>
  <strong>Auxilio:</strong>
  <%= @liquidacion.auxilio %>
</p>

<p>
  <strong>Horas ex diur:</strong>
  <%= @liquidacion.horas_ex_diur %>
</p>

<p>
  <strong>Horas ex noc:</strong>
  <%= @liquidacion.horas_ex_noc %>
</p>

<p>
  <strong>Recargos noc:</strong>
  <%= @liquidacion.recargos_noc %>
</p>

<p>
  <strong>Domi ordinarios:</strong>
  <%= @liquidacion.domi_ordinarios %>
</p>

<p>
  <strong>Horas ex domi diur:</strong>
  <%= @liquidacion.horas_ex_domi_diur %>
</p>

<p>
  <strong>Horas ex domi noc:</strong>
  <%= @liquidacion.horas_ex_domi_noc %>
</p>

<p>
  <strong>Otros:</strong>
  <%= @liquidacion.otros %>
</p>

<p>
  <strong>Concepto otros:</strong>
  <%= @liquidacion.concepto_otros %>
</p>

<p>
  <strong>Sueldo promedio:</strong>
  <%= @liquidacion.sueldo_promedio %>
</p>

<p>
  <strong>Prima extra:</strong>
  <%= @liquidacion.prima_extra %>
</p>

<p>
  <strong>Valor mes:</strong>
  <%= @liquidacion.valor_mes %>
</p>

<p>
  <strong>Valor día:</strong>
  <%= @liquidacion.valor_dia %>
</p>

<p>
  <strong>Valor hora:</strong>
  <%= @liquidacion.valor_hora %>
</p>

<p>
  <strong>Recargo nocturno:</strong>
  <%= @liquidacion.recargo_nocturno %>
</p>

<p>
  <strong>Hora extra diurna:</strong>
  <%= @liquidacion.hora_extra_diurna %>
</p>

<p>
  <strong>Hora extra nocturna:</strong>
  <%= @liquidacion.hora_extra_nocturna %>
</p>

<p>
  <strong>Hora ordinaria dominical:</strong>
  <%= @liquidacion.hora_ordinaria_dominical %>
</p>

<p>
  <strong>Hora extra dominical diurna:</strong>
  <%= @liquidacion.hora_extra_dominical_diurna %>
</p>

<p>
  <strong>Hora extra dominical nocturna:</strong>
  <%= @liquidacion.hora_extra_dominical_nocturna %>
</p>

<p>
  <strong>Fecha ini vacas:</strong>
  <%= @liquidacion.fecha_ini_vacas %>
</p>

<p>
  <strong>Fecha fin vacas:</strong>
  <%= @liquidacion.fecha_fin_vacas %>
</p>

<p>
  <strong>Vacaciones:</strong>
  <%= @liquidacion.vacaciones %>
</p>

<p>
  <strong>Indemniza art65:</strong>
  <%= @liquidacion.indemniza_art65 %>
</p>

<p>
  <strong>Indemniza art64:</strong>
  <%= @liquidacion.indemniza_art64 %>
</p>

<p>
  <strong>Calc art64:</strong>
  <%= @liquidacion.calc_art64 %>
</p>

<p>
  <strong>Check65:</strong>
  <%= @liquidacion.check65 %>
</p>

<p>
  <strong>Fecha ini pactada:</strong>
  <%= @liquidacion.fecha_ini_pactada %>
</p>

<p>
  <strong>Fecha fin pactada:</strong>
  <%= @liquidacion.fecha_fin_pactada %>
</p>

<p>
  <strong>Num pro:</strong>
  <%= @liquidacion.num_pro %>
</p>

<p>
  <strong>Fecha ini pro1:</strong>
  <%= @liquidacion.fecha_ini_pro1 %>
</p>

<p>
  <strong>Date:</strong>
  <%= @liquidacion.date %>
</p>

<p>
  <strong>Fecha ini pro2:</strong>
  <%= @liquidacion.fecha_ini_pro2 %>
</p>

<p>
  <strong>Fecha ini pro3:</strong>
  <%= @liquidacion.fecha_ini_pro3 %>
</p>

<p>
  <strong>Fecha ini pro4:</strong>
  <%= @liquidacion.fecha_ini_pro4 %>
</p>

<p>
  <strong>Fecha fin pro1:</strong>
  <%= @liquidacion.fecha_fin_pro1 %>
</p>

<p>
  <strong>Fecha fin pro2:</strong>
  <%= @liquidacion.fecha_fin_pro2 %>
</p>

<p>
  <strong>Fecha fin pro3:</strong>
  <%= @liquidacion.fecha_fin_pro3 %>
</p>

<p>
  <strong>Fecha fin pro4:</strong>
  <%= @liquidacion.fecha_fin_pro4 %>
</p>

<p>
  <strong>Fecha ini presta:</strong>
  <%= @liquidacion.fecha_ini_presta %>
</p>

<p>
  <strong>Fecha fin presta:</strong>
  <%= @liquidacion.fecha_fin_presta %>
</p>

<p>
  <strong>Cesantias:</strong>
  <%= @liquidacion.cesantias %>
</p>

<p>
  <strong>Inte cesantias:</strong>
  <%= @liquidacion.inte_cesantias %>
</p>

<p>
  <strong>Prima:</strong>
  <%= @liquidacion.prima %>
</p>

<p>
  <strong>Total prestaciones:</strong>
  <%= @liquidacion.total_prestaciones %>
</p>

<p>
  <strong>Sueldo pendiente:</strong>
  <%= @liquidacion.sueldo_pendiente %>
</p>

<p>
  <strong>Aux pendiente:</strong>
  <%= @liquidacion.aux_pendiente %>
</p>

<p>
  <strong>Reajuste pendiente:</strong>
  <%= @liquidacion.reajuste_pendiente %>
</p>

<p>
  <strong>Otros pendiente:</strong>
  <%= @liquidacion.otros_pendiente %>
</p>

<p>
  <strong>Total pendiente:</strong>
  <%= @liquidacion.total_pendiente %>
</p>

<p>
  <strong>Total :</strong>
  <%= @liquidacion.total %>
</p>

<p>
  <strong>Nombres:</strong>
  <%= @liquidacion.nombres %>
</p>

<p>
  <strong>Correo:</strong>
  <%= @liquidacion.correo %>
</p>

<p>
  <strong>Fecha creación:</strong>
  <%= @liquidacion.created_at %>
</p>


<%= link_to 'Edit', edit_liquidacion_path(@liquidacion) %> |
<%= link_to 'Back', liquidacions_path %>